#!/usr/bin/env bash
# Configures Nginx to run as the nginx user listening on port 8080

# Change user to nginx in main configuration
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf

# Change listening port from 80 to 8080 in default site config
sed -i 's/listen 80/listen 8080/g' /etc/nginx/sites-available/default

# Restart service to apply changes
service nginx restart
