#!/usr/bin/env bash
# Installs and configures HAProxy to load-balance across web-01 and web-02
apt-get update -y
apt-get install -y haproxy
printf '%s\n' "ENABLED=1" > /etc/default/haproxy
cat > /etc/haproxy/haproxy.cfg << 'HAPROXY'
global
	log /dev/log local0
	log /dev/log local1 notice
	chroot /var/lib/haproxy
	user haproxy
	group haproxy
	daemon
	maxconn 256
defaults
	log global
	mode http
	option httplog
	option dontlognull
	timeout connect 5000
	timeout client 50000
	timeout server 50000
frontend http_front
	bind *:80
	default_backend web_servers
backend web_servers
	balance roundrobin
	server 7141-web-01 3.82.243.236:80 check
	server 7141-web-02 44.210.112.183:80 check
HAPROXY
haproxy -c -f /etc/haproxy/haproxy.cfg
service haproxy restart
