#!/usr/bin/env bash
# Installs and configures HAProxy to load-balance across web-01 and web-02
apt-get update -y
apt-get install -y haproxy

printf "%s\n" \
"frontend http_front" \
"	bind *:80" \
"	default_backend http_back" \
"" \
"backend http_back" \
"	balance roundrobin" \
"	server 7141-web-01 3.82.243.236:80 check" \
"	server 7141-web-02 WEB02_IP:80 check" \
>> /etc/haproxy/haproxy.cfg

echo "ENABLED=1" > /etc/default/haproxy
service haproxy restart
