#!/usr/bin/env bash
# Fixes the Nginx default site link and restarts Nginx on port 80

rm -f /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
