#!/usr/bin/env bash
# Configures Nginx to redirect /redirect_me with a 301 Moved Permanently
apt-get update -y
apt-get install -y nginx
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html

printf "%s\n" \
"server {" \
"	listen 80 default_server;" \
"	listen [::]:80 default_server;" \
"	root /var/www/html;" \
"	index index.html index.htm index.nginx-debian.html;" \
"	server_name _;" \
"" \
"	location / {" \
"		try_files \$uri \$uri/ =404;" \
"	}" \
"" \
"	location /redirect_me {" \
"		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;" \
"	}" \
"}" > /etc/nginx/sites-available/default

service nginx restart
