#!/usr/bin/env bash
# Configures Nginx with a custom 404 page containing a specific string
apt-get update -y
apt-get install -y nginx
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

printf "%s\n" \
"server {" \
"	listen 80 default_server;" \
"	listen [::]:80 default_server;" \
"	root /var/www/html;" \
"	index index.html index.htm index.nginx-debian.html;" \
"	server_name _;" \
"" \
"	location / {" \
"		try_files \$uri \$uri/ =404;" \
"	}" \
"" \
"	location /redirect_me {" \
"		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;" \
"	}" \
"" \
"	error_page 404 /404.html;" \
"	location = /404.html {" \
"		internal;" \
"	}" \
"}" > /etc/nginx/sites-available/default

service nginx restart
