#!/usr/bin/env bash
# Configures Nginx with a custom 404 page containing a specific string
apt-get update -y
apt-get install -y nginx
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

redirect="location /redirect_me {\n\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}\n"
error_page="error_page 404 /404.html;\n\tlocation = /404.html {\n\t\tinternal;\n\t}\n"
sed -i "/server_name _;/a \\\t$redirect\t$error_page" /etc/nginx/sites-available/default

service nginx restart
